# Generated by Django 5.2.3 on 2025-06-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SRCMS", "0002_alter_complaint_passenger_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="created_at",
        ),
    ]
