# Generated by Django 5.2.3 on 2025-06-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SRCMS", "0003_remove_complaint_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=50, unique=True)),
                ("user_query", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("sub_category", models.CharField(max_length=100)),
                ("expected_output", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
