# Generated by Django 5.2.3 on 2025-06-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SRCMS", "0004_queryresponse"),
    ]

    operations = [
        migrations.RenameField(
            model_name="queryresponse",
            old_name="expected_output",
            new_name="suggested_response",
        ),
        migrations.RemoveField(
            model_name="queryresponse",
            name="created_at",
        ),
    ]
