# Generated by Django 5.2.3 on 2025-06-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "SRCMS",
            "0005_rename_expected_output_queryresponse_suggested_response_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="queryresponse",
            old_name="sub_category",
            new_name="subcategory",
        ),
    ]
