# Generated by Django 5.2.3 on 2025-06-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SRCMS", "0006_rename_sub_category_queryresponse_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queryresponse",
            name="external_id",
            field=models.IntegerField(unique=True),
        ),
    ]
